### PR TITLE
Change dependency to use maas-schemas 10.0.1

### PR DESCRIPTION
**Pull request by huksley**
We have deployed new version of maas-schemas 🎉
Time to fix dependency here.

### CODE REVIEW

**Comment by cyberixae** [comment]
Would this pull request be the time to figure out how to synchronise the release of the two schema packages?

**Comment by huksley** [comment]
@cyberixae I think it is a good idea! Any thoughts on how to do it?

**Comment by huksley** [comment]
If you dont mind, @cyberixae I'll go ahead and merge this and we will define later how to sync maas-schemas and maas-schemas-ts packages, ok?

**Comment by cyberixae** [comment]
> If you dont mind, @cyberixae I'll go ahead and merge this and we will define later how to sync maas-schemas and maas-schemas-ts packages, ok?

Sure

**Pull request merged**
